# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# copied from dplyr

language: r
r: bioc-devel
sudo: false
cache: packages

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

before_script:
- mkdir -p ~/.R; echo 'PKG_CXXFLAGS := ${PKG_CXXFLAGS} -Wall -Wextra -pedantic -Werror' > ~/.R/Makevars
